### PR TITLE
Use requestAnimtionFrame

### PR DESCRIPTION
**Pull request by mikkelkai**
Use requestAnimtionFrame for better performance in modern browsers and add polyfill for older.

### CODE REVIEW

**Comment by lmgonzalves** [comment]
Hi @mikkelkai, this is great!
But this improvement is breaking some animations that I had done.
I'm trying to find out why it is not working properly. Maybe I'll prepare a demo to show you the issue.
Your pull request is very welcome anyway :)
Looking forward to merge this!

**Comment by mikkelkai** [comment]
That's unfortunate, but i would be happy to help you fix it :)

**Comment by lmgonzalves** [comment]
I've created 2 demos to show you how an animation work with and without the pull request.
Seems to be a Firefox issue. It's working properly in Chrome (not tested in others browsers).

Demo original: http://jsfiddle.net/lmgonzalves/e2vbuaz6/1/
Demo with the pull request included: http://jsfiddle.net/lmgonzalves/ptzz2x4k/2/

Note the unwanted delay in the second demo (only Firefox).

**Comment by mikkelkai** [comment]
The error seems to happen because of how firefox handles the callback (works fine in safari too). 
Demo with setInterval instead of callback: https://jsfiddle.net/s8qoeg6y/
I can't look at it anymore right now, but i'll likely look in to i later today :)

**Comment by lmgonzalves** [comment]
Good fix man!
But I need to get it working using `callback` too.
I really appreciate your efforts to help :+1:

**Comment by mikkelkai** [comment]
It seems that firefox was stopping the current animationFrame function when calling cancelAnimationFrame from it. Anyway the bug should be fixed now :)

**Comment by lmgonzalves** [comment]
@mikkelkai 
I've experimenting a very strange behavior with `requestAnimationFrame`. You can see the details in [this StackOverflow question](http://stackoverflow.com/questions/35468440/buggy-behavior-using-requestanimationframe), and also you can check the demos:
- [setTimeout Demo](https://jsfiddle.net/lmgonzalves/orvtzk5t/1/) (working properly)
- [requestAnimationFrame Demo](https://jsfiddle.net/lmgonzalves/gjpx0s9L/2/) (buggy behavior)

Can you help me with this? I really have no idea what's going on, so any help is welcome :)

**Comment by lmgonzalves** [comment]
Solved! [Here is the answer](http://stackoverflow.com/a/35644562/4908989) :)

**Comment by mikkelkai** [comment]
Nice, sorry i didn't get around to look at it

**Pull request merged**
